@startuml

title Youtube media controller - Queue intent

| Android intergration - Any View |
:On long press
:Show available share intents
:Execute "Queue video" Intent;
:Check if intent content contains URL youtube host;
if (Contains youtube hostname) then (yes)
:Call localhost queue endpoint with youtube url as URL param;
else (no)
:Ignore intent;
stop
end if

| Nodejs app - Host server | 
:On /queue/:videoId request;
:Check if playback has ended;
if (playback has ended) then (yes)
:Send websocket play request to Chrome extension;
else (no)
:Add videoId to queue;
end if

| Video render - Brave browser (chromiuim) |
:on YT video start;
:Start playback watcher;

repeat
:Notify nodejs app current playback position via websocket;
repeat while (current playback possition is less than playback length) is (yes) not (no)
:Notify nodejs app playback has ended via websocket;


| Nodejs app - Host server | 
:On playback ended WS event
:Check queue;
if (queue contains videoID) then (yes)
:Send websocket play request to Chrome extension;
:pop queue;
stop;
else (no)
stop
end if

@enduml