<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>YTMediaControllerUpdaterSrv</RootNamespace>
    <AssemblyName>YTMediaControllerUpdaterSrv</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWindowsForms>false</UseWindowsForms>
    <UseWPF>false</UseWPF>
    <Deterministic>true</Deterministic>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DefineConstants>TRACE;DEBUG</DefineConstants>
    <OutputPath>bin\Debug\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Stable'">
    <DefineConstants>STABLE;</DefineConstants>
    <OutputPath>bin\Release\</OutputPath>
    <Optimize>true</Optimize>
    <DebugType>pdbonly</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Beta'">
    <DefineConstants>BETA;</DefineConstants>
    <OutputPath>bin\Beta\</OutputPath>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Alpha'">
    <DefineConstants>ALPHA;</DefineConstants>
    <OutputPath>bin\Alpha\</OutputPath>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Stable' OR '$(Configuration)' == 'Beta' OR '$(Configuration)' == 'Alpha'">
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishTrimmed>false</PublishTrimmed>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="9.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Octokit" Version="14.0.0" />
    <PackageReference Include="Semver" Version="3.0.0" />
    <PackageReference Include="TaskScheduler" Version="2.12.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\YTMediaControllerSrv\YTMediaControllerSrv.csproj" />
  </ItemGroup>


</Project>
