name: Release mobile apps

on:
  workflow_run:
    workflows: ["Build Desktop Installer"]
    types:
      - in_progress

permissions:
  contents: write

jobs:
  android-build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version/tag variable
        if: github.ref_name == 'main' || github.ref_name == 'staging'
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            TAG_TYPE="prod"
          else
            TAG_TYPE="rc"
          fi
          VERSION="v1.0.0-${TAG_TYPE}.${{ github.run_number }}"
          echo "TAG_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - name: Cache Gradle files
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key:
            gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*',
            '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Make gradlew executable
        run: chmod +x ./mobile/android/gradlew

      - name: Build Release APK
        run: ./mobile/android/gradlew assembleRelease

      - name: Upload Release APK to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_VERSION }}
          files: mobile/android/app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
