name: Build assets

on:
  push:
    branches: ["main", "staging", "android-pipeline-testing"]

permissions:
  contents: write

jobs:
  create-tag-and-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set version/tag variable
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            TAG_TYPE="prod"
          else
            TAG_TYPE="rc"
          fi
          VERSION="v1.0.0-${TAG_TYPE}.${{ github.run_number }}"
          echo "TAG_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create Git tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${TAG_VERSION}
          git push origin ${TAG_VERSION}
        shell: bash

  trigger-desktop:
    name: Trigger Desktop Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Desktop Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: build-desktop
          client-payload: '{"tag": "${{ env.TAG_VERSION }}"}'

  trigger-mobile:
    name: Trigger Mobile Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Mobile Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: build-mobile
          client-payload: '{"tag": "${{ env.TAG_VERSION }}"}'
