name: Build assets
on:
  push:
    branches: ["main", "pipeline-testing"]

jobs:
  build-desktop-installer-asset:
    runs-on: windows-server

    steps:
      - uses: actions/checkout@v4

      - name: Set version/tag variable
        id: vars
        run: |
          VERSION="v1.0.0-build.${{ github.run_number }}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Fetch external binaries
        run: node ./backend/scripts/installExternalDeps.js

      - name: Install NPM modules
        run: npm install

      - name: Restore NuGet packages
        run: |
          nuget restore ./backend/YTMediaControllerSrv/YTMediaControllerSrv.sln

      - name: Build backend service
        run:
          msbuild ./backend/YTMediaControllerSrv/YTMediaControllerSrv.sln
          /p:Configuration=Release

      - name: Build installer
        run: npm run package

      - name: Create Git tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.vars.outputs.version }}
          git push origin ${{ steps.vars.outputs.version }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.vars.outputs.version }}
          release_name: Release ${{ steps.vars.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload installer asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/YoutubeMediaControllerInstaller.exe
          asset_name: YoutubeMediaControllerInstaller.exe
          asset_content_type: application/octet-stream
